master:
  image: redis
  environment:
    - affinity:service!=slave1
    - affinity:service!=slave2
  restart: always
  container_name: master
  
slave1:
  links:
    - master:redis-master
  image: redis
  command: redis-server --slaveof redis-master 6379
  environment:
    - affinity:service!=master
    - affinity:service!=slave1
  container_name: slave1
  
slave2:
  image: redis
  links:
    - master:redis-master
  command: redis-server --slaveof redis-master 6379
  environment:
    - affinity:service!=master
    - affinity:service!=slave2
  container_name: slave2


  labels: 
    scale: "3"
  restart: always
  links:
    - master:redis-master
sentinel:
  image: registry.aliyuncs.com/acs-sample/redis-sentinel
  environment:
    - affinity:service!=sentinel
  labels: 
    scale: "4"
  restart: always
  links:
    - master:redis-master
    - slave1
    - slave2


